# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/ginopane/blogtaxonomy/models/series/columns.yaml

# Model Class name
modelClass: GinoPane\BlogTaxonomy\Models\Series

# List Title
title: ginopane.blogtaxonomy::lang.form.series.list_title

# Link URL for each record
recordUrl: ginopane/blogtaxonomy/series/update/:id

# Message to display if the list is empty
noRecordsMessage: ginopane.blogtaxonomy::lang.form.series.no_series_message

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

# Filter widget configuration
filter: config_filter.yaml
