# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/ginopane/blogtaxonomy/models/tag/columns.yaml

# Model Class name
modelClass: GinoPane\BlogTaxonomy\Models\Tag

# List Title
title: ginopane.blogtaxonomy::lang.form.tags.list_title

# Link URL for each record
recordUrl: ginopane/blogtaxonomy/tags/update/:id

# Message to display if the list is empty
noRecordsMessage: ginopane.blogtaxonomy::lang.form.tags.no_tags_message

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: name
    direction: asc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
